name: Deploy to Windows VPS (C:\web)

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: [self-hosted, Windows]

    # ép toàn bộ script dùng PowerShell 5.1 thay vì pwsh
    defaults:
      run:
        shell: powershell

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node 20
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install deps & build (in workspace)
        run: |
          cd $env:GITHUB_WORKSPACE
          npm ci
          npm run build --if-present

      - name: Sync code to C:\web (mirror but keep .env)
        run: |
          $src = "$env:GITHUB_WORKSPACE\"
          $dst = "C:\web\"
          robocopy $src $dst /MIR /XD ".git" "node_modules" ".github" /XF ".env"
          if ($LASTEXITCODE -ge 8) { throw "RoboCopy failed with exit code $LASTEXITCODE" }

      - name: Install production deps in C:\web
        working-directory: C:\web
        run: |
          npm ci --omit=dev

      - name: Start/Reload PM2 app "server"
        run: |
          $pm2 = (Get-Command pm2 -ErrorAction SilentlyContinue)
          if (-not $pm2) {
            $pm2cmd = "$env:APPDATA\npm\pm2.cmd"
            if (Test-Path $pm2cmd) { $env:Path += ";$([System.IO.Path]::GetDirectoryName($pm2cmd))" }
          }

          pm2 list | findstr /C:"server"
          if ($LASTEXITCODE -eq 0) {
            pm2 reload server
          } else {
            pm2 start C:\web\server.js --name server
          }
          pm2 save
