name: Deploy to Windows VPS (C:\web)

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: [self-hosted, Windows]   # khớp label runner của bạn

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node 20
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install deps & build (in workspace)
        shell: powershell
        run: |
          cd $env:GITHUB_WORKSPACE
          npm ci
          npm run build --if-present

      - name: Sync code to C:\web (mirror but keep .env)
        shell: powershell
        run: |
          $src = "$env:GITHUB_WORKSPACE\"
          $dst = "C:\web\"
          robocopy $src $dst /MIR /XD ".git" "node_modules" ".github" "tests" /XF ".env"
          if ($LASTEXITCODE -ge 8) { throw "RoboCopy failed with exit code $LASTEXITCODE" }

      - name: Install production deps in C:\web
        shell: powershell
        working-directory: C:\web
        run: |
          npm ci --omit=dev

      - name: Start/Reload PM2 app "server"
        shell: powershell
        run: |
          pm2 list | findstr /C:"server"
          if ($LASTEXITCODE -eq 0) {
            pm2 reload server
          } else {
            pm2 start C:\web\server.js --name server
          }
          pm2 save
