name: Deploy to Windows VPS

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies and generate lock file
        shell: cmd
        run: |
          npm install

      - name: Copy files to deployment folder
        shell: cmd
        run: |
          if not exist "%USERPROFILE%\web" mkdir "%USERPROFILE%\web"
          copy "%GITHUB_WORKSPACE%\server.js" "%USERPROFILE%\web\"
          copy "%GITHUB_WORKSPACE%\package.json" "%USERPROFILE%\web\"
          if exist "%GITHUB_WORKSPACE%\package-lock.json" copy "%GITHUB_WORKSPACE%\package-lock.json" "%USERPROFILE%\web\"
          copy "%GITHUB_WORKSPACE%\*.html" "%USERPROFILE%\web\"
          copy "%GITHUB_WORKSPACE%\*.mobileconfig" "%USERPROFILE%\web\"
          copy "%GITHUB_WORKSPACE%\*.md" "%USERPROFILE%\web\"
          copy "%GITHUB_WORKSPACE%\*.bat" "%USERPROFILE%\web\"
          copy "%GITHUB_WORKSPACE%\*.sh" "%USERPROFILE%\web\"
          if exist "%GITHUB_WORKSPACE%\data" xcopy /E /I /Y "%GITHUB_WORKSPACE%\data" "%USERPROFILE%\web\data\"
          if exist "%USERPROFILE%\web\.env" del "%USERPROFILE%\web\.env"

      - name: Install production dependencies
        shell: cmd
        run: |
          cd /d "%USERPROFILE%\web"
          npm ci --omit=dev

      - name: Create startup script
        shell: cmd
        run: |
          echo @echo off > "%USERPROFILE%\web\start-server.bat"
          echo cd /d "%USERPROFILE%\web" >> "%USERPROFILE%\web\start-server.bat"
          echo node server.js >> "%USERPROFILE%\web\start-server.bat"

      - name: Stop and restart application
        shell: cmd
        run: |
          taskkill /F /IM node.exe 2>nul || echo "No Node.js processes running"
          timeout /t 2 /nobreak >nul
          cd /d "%USERPROFILE%\web"
          if exist "data\database.json" (
            echo Database exists, starting server...
            start /B node server.js
          ) else (
            echo Database not found, initializing...
            node server.js
          )