name: Deploy to Windows VPS (C:\web)

on:
  push:
    branches: [ "main" ]   # đổi nếu bạn deploy nhánh khác

jobs:
  deploy:
    runs-on: self-hosted    # dùng runner đang cài trong VPS Windows của bạn

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node 20
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      # (Tuỳ dự án) Build trước rồi mới copy, nếu bạn có bước build
      - name: Install deps & build (in workspace)
        shell: pwsh
        run: |
          cd $env:GITHUB_WORKSPACE
          npm ci
          npm run build --if-present

      - name: Sync code to C:\web (mirror but keep .env)
        shell: pwsh
        run: |
          $src = "$env:GITHUB_WORKSPACE\"
          $dst = "C:\web\"
          # Mirror nhưng bỏ các thư mục không cần và KHÔNG đè .env trên server
          robocopy $src $dst /MIR /XD ".git" "node_modules" ".github" "tests" /XF ".env" | Out-Null

      - name: Install production deps in C:\web
        shell: pwsh
        working-directory: C:\web
        run: |
          npm ci --omit=dev

      - name: Start/Reload PM2 app "server"
        shell: pwsh
        run: |
          pm2 list | findstr /C:"server"
          if ($LASTEXITCODE -eq 0) {
            pm2 reload server
          } else {
            pm2 start C:\web\server.js --name server
          }
          pm2 save
