name: Deploy to Windows VPS

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        shell: cmd
        run: |
          npm ci

      - name: Copy files to C:\web
        shell: cmd
        run: |
          if not exist "C:\web" mkdir "C:\web"
          copy "%GITHUB_WORKSPACE%\server.js" "C:\web\"
          copy "%GITHUB_WORKSPACE%\package.json" "C:\web\"
          copy "%GITHUB_WORKSPACE%\*.html" "C:\web\"
          copy "%GITHUB_WORKSPACE%\*.mobileconfig" "C:\web\"
          copy "%GITHUB_WORKSPACE%\*.md" "C:\web\"
          copy "%GITHUB_WORKSPACE%\*.bat" "C:\web\"
          copy "%GITHUB_WORKSPACE%\*.sh" "C:\web\"
          if exist "C:\web\.env" del "C:\web\.env"

      - name: Install production dependencies
        shell: cmd
        run: |
          cd /d C:\web
          npm ci --omit=dev

      - name: Restart PM2 application
        shell: cmd
        run: |
          pm2 stop server 2>nul || echo "App not running"
          pm2 start C:\web\server.js --name server
          pm2 save