name: Deploy to Windows VPS

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        shell: cmd
        run: |
          npm ci

      - name: Copy files to deployment folder
        shell: cmd
        run: |
          if not exist "%USERPROFILE%\web" mkdir "%USERPROFILE%\web"
          copy "%GITHUB_WORKSPACE%\server.js" "%USERPROFILE%\web\"
          copy "%GITHUB_WORKSPACE%\package.json" "%USERPROFILE%\web\"
          copy "%GITHUB_WORKSPACE%\*.html" "%USERPROFILE%\web\"
          copy "%GITHUB_WORKSPACE%\*.mobileconfig" "%USERPROFILE%\web\"
          copy "%GITHUB_WORKSPACE%\*.md" "%USERPROFILE%\web\"
          copy "%GITHUB_WORKSPACE%\*.bat" "%USERPROFILE%\web\"
          copy "%GITHUB_WORKSPACE%\*.sh" "%USERPROFILE%\web\"
          if exist "%USERPROFILE%\web\.env" del "%USERPROFILE%\web\.env"

      - name: Install production dependencies
        shell: cmd
        run: |
          cd /d "%USERPROFILE%\web"
          npm ci --omit=dev

      - name: Restart PM2 application
        shell: cmd
        run: |
          pm2 stop server 2>nul || echo "App not running"
          pm2 start "%USERPROFILE%\web\server.js" --name server
          pm2 save